# Generated by Django 2.2.4 on 2019-08-04 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinobi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='genero',
            field=models.CharField(choices=[('MA', 'Masculino'), ('FE', 'Feminino'), ('OU', 'Outros')], default='', max_length=25, verbose_name='Gênero'),
        ),
    ]
