# Generated by Django 2.2.4 on 2019-08-04 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shinobi', '0002_cadastro_genero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastro',
            old_name='Sobrenome',
            new_name='sobrenome',
        ),
    ]
