# Generated by Django 2.2.4 on 2019-08-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinobi', '0003_auto_20190804_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='confirmar_senha',
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='genero',
            field=models.CharField(choices=[('MA', 'Masculino'), ('FE', 'Feminino'), ('OU', 'Outros')], max_length=25, verbose_name='Gênero'),
        ),
    ]
