# Generated by Django 2.2.4 on 2019-08-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinobi', '0004_auto_20190804_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='E-mail'),
        ),
    ]
